DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT(
   ID INTEGER PRIMARY KEY AUTO_INCREMENT,
   NR VARCHAR(20),
   NAME VARCHAR(20),
   SALDO FLOAT(5,2),
   CURRENCY VARCHAR(20)
   );

INSERT INTO ACCOUNT VALUES(1, '120-1', 'Sparkonto', 100.50, 'CHF');
INSERT INTO ACCOUNT VALUES(2, '120-2', 'Privatkonto', 580.20, 'CHF');
INSERT INTO ACCOUNT VALUES(3, '120-3', 'Eurokonto', 205.00, 'EUR');
INSERT INTO ACCOUNT VALUES(4, '120-4', 'Dollarkonto', 305.10, 'USD');


