DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT(
   ID INTEGER PRIMARY KEY AUTO_INCREMENT,
   NR VARCHAR(20),
   NAME VARCHAR(20),
   SALDO FLOAT(5,2),
   CURRENCY VARCHAR(20)
   );



